/**
 * Dummy course data for the purposes of testing
 * Contains all courseSections of CPSC 100 and CPSC 121 in term 1
 */

export const testData = [
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1C",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "17:30",
    endtime: "18:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1R",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "9:00",
    endtime: "10:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1E",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "16:00",
    endtime: "17:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1M",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Thu",
    starttime: "12:30",
    endtime: "13:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1E",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "16:00",
    endtime: "17:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1T",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "11:00",
    endtime: "12:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1H",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "14:00",
    endtime: "15:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1N",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "11:00",
    endtime: "12:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1K",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Thu",
    starttime: "8:30",
    endtime: "9:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1A",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "12:30",
    endtime: "13:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1R",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "9:00",
    endtime: "10:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1A",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "12:30",
    endtime: "13:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1N",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "11:00",
    endtime: "12:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1C",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "17:30",
    endtime: "18:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1T",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "11:00",
    endtime: "12:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1G",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "14:30",
    endtime: "15:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1V",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Fri",
    starttime: "9:00",
    endtime: "10:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1J",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "13:30",
    endtime: "14:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 1W1",
    status: "Blocked",
    activity: "Waiting List",
    prof: "",
    term: "1",
    day: "Tue Thu",
    starttime: "15:30",
    endtime: "17:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1D",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "15:00",
    endtime: "16:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1S",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "17:00",
    endtime: "18:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1G",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "14:30",
    endtime: "15:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1Z",
    status: "Full",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Fri",
    starttime: "10:00",
    endtime: "11:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1H",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "14:00",
    endtime: "15:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1Z",
    status: "Full",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Fri",
    starttime: "10:00",
    endtime: "11:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1K",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Thu",
    starttime: "8:30",
    endtime: "9:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 1W2",
    status: "Blocked",
    activity: "Waiting List",
    prof: "",
    term: "1",
    day: "Tue Thu",
    starttime: "9:30",
    endtime: "11:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1J",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Tue",
    starttime: "13:30",
    endtime: "14:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 102",
    status: "Restricted",
    activity: "Web-Oriented Course",
    prof: "OLA, OLUWAKEMI",
    term: "1",
    day: "Wed",
    starttime: "9:30",
    endtime: "11:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1P",
    status: "Full",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "13:00",
    endtime: "14:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 101",
    status: "Restricted",
    activity: "Web-Oriented Course",
    prof: "WONG, JESSICA",
    term: "1",
    day: "Tue Thu",
    starttime: "15:30",
    endtime: "17:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1M",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Thu",
    starttime: "12:30",
    endtime: "13:30"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1B",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "12:00",
    endtime: "13:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1S",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "17:00",
    endtime: "18:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1B",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "12:00",
    endtime: "13:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1P",
    status: "Full",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "13:00",
    endtime: "14:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1D",
    status: "",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Wed",
    starttime: "15:00",
    endtime: "16:00"
    },
    {
    coursetitle: "CPSC 100 Computational Thinking",
    coursedept: "CPSC",
    coursenumber: "100",
    sectiontitle: "CPSC 100 L1V",
    status: "Blocked",
    activity: "Laboratory",
    prof: "",
    term: "1",
    day: "Fri",
    starttime: "9:00",
    endtime: "10:00"
    },
    {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1G",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1S",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "18:00",
        endtime: "20:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1D",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "15:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1P",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "13:00",
        endtime: "14:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1H",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1T",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "15:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1E",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 103",
        status: "Full",
        activity: "Web-Oriented Course",
        prof: "MOCHETTI DE MAGALHAES, KARINA",
        term: "1",
        day: "Tue Thu",
        starttime: "9:30",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1K",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1V",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1G",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "16:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 1W2",
        status: "Blocked",
        activity: "Waiting List",
        prof: "",
        term: "1",
        day: "Tue Thu",
        starttime: "15:30",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1C",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "17:30",
        endtime: "19:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1N",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "12:00",
        endtime: "14:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Z",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1L",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "12:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1F",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "15:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1R",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1C",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "17:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1P",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "13:00",
        endtime: "14:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1H",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1T",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "15:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1E",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1R",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "15:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1D",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1P",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1A",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "9:00",
        endtime: "10:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1M",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1R",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "15:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1J",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1U",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1F",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "12:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1A",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1L",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1X",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1H",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "14:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1H",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1T",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "15:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1E",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 102",
        status: "Full",
        activity: "Web-Oriented Course",
        prof: "MOCHETTI DE MAGALHAES, KARINA",
        term: "1",
        day: "Tue Thu",
        starttime: "15:30",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1K",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1V",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1G",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "16:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1B",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "13:30",
        endtime: "15:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1M",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Y",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1J",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "13:30",
        endtime: "14:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1J",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1U",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1G",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "16:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1B",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "13:30",
        endtime: "15:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1M",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Y",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1J",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "13:30",
        endtime: "14:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1D",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1P",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1A",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "9:00",
        endtime: "10:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1L",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "12:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 101",
        status: "Full",
        activity: "Web-Oriented Course",
        prof: "BELLEVILLE, PATRICE",
        term: "1",
        day: "Tue Thu",
        starttime: "17:00",
        endtime: "18:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1K",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1V",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1H",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "14:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1C",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "17:30",
        endtime: "19:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1N",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "12:00",
        endtime: "14:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Z",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1K",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "18:00",
        endtime: "19:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1M",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1G",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1S",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "18:00",
        endtime: "20:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1D",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "15:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1P",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "13:00",
        endtime: "14:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 1W3",
        status: "Blocked",
        activity: "Waiting List",
        prof: "",
        term: "1",
        day: "Tue Thu",
        starttime: "9:30",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1B",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "13:30",
        endtime: "15:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1M",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Y",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1K",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "18:00",
        endtime: "19:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1E",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "14:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Q",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "17:00",
        endtime: "19:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1B",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "17:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1N",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1E",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "14:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Q",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "17:00",
        endtime: "19:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1B",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "17:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1M",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1E",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "14:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Q",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "17:00",
        endtime: "19:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1B",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "17:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1N",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1G",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1S",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "18:00",
        endtime: "20:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1D",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "15:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1R",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "15:00",
        endtime: "16:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1J",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1U",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1F",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "12:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 1W1",
        status: "Blocked",
        activity: "Waiting List",
        prof: "",
        term: "1",
        day: "Tue Thu",
        starttime: "17:00",
        endtime: "18:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1F",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "15:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1R",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1C",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "17:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1F",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "12:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1A",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1L",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1X",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1H",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "14:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1C",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "17:30",
        endtime: "19:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1N",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "12:00",
        endtime: "14:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1Z",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "11:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1K",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "18:00",
        endtime: "19:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1A",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1L",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Wed",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1X",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1J",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Tue",
        starttime: "13:30",
        endtime: "14:30"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1D",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "13:00",
        endtime: "15:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1P",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "16:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1A",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "9:00",
        endtime: "10:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1L",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "12:00",
        endtime: "13:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1F",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "15:00",
        endtime: "17:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 L1R",
        status: "",
        activity: "Laboratory",
        prof: "",
        term: "1",
        day: "Thu",
        starttime: "9:00",
        endtime: "11:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1C",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Mon",
        starttime: "17:00",
        endtime: "18:00"
        },
        {
        coursetitle: "CPSC 121 Models of Computation",
        coursedept: "CPSC",
        coursenumber: "121",
        sectiontitle: "CPSC 121 T1N",
        status: "",
        activity: "Tutorial",
        prof: "",
        term: "1",
        day: "Fri",
        starttime: "11:00",
        endtime: "12:00"
        },
        {
        coursetitle: "HIST 100 What is History?",
        coursedept:	"HIST",
        coursenumber: "100",
        sectiontitle: "HIST 100 201",
        status:	"",
        activity: "Web-Oriented Course",
        prof: "FRENCH, WILLIAM EARL",
        term: "2",
        day: "Tue Thu",
        starttime: "14:00",
        endtime: "15:30"
    },
    {
        coursetitle: "HIST 100 What is History?",
        coursedept:	"HIST",
        coursenumber: "100",
        sectiontitle: "HIST 100 L1B",
        status:	"",
        activity: "Discussion",
        prof: "",
        term: "2",
        day: "Fri",
        starttime: "11:00",
        endtime: "12:00",
    },
    {
        coursetitle: "HIST 100 What is History?",
        coursedept:	"HIST",
        coursenumber: "100",
        sectiontitle: "HIST 100 L1A",
        status:	"",
        activity: "Discussion",
        prof: "",
        term: "2",
        day: "Thu",
        starttime: "15:30",
        endtime: "16:30"
    },
    {
        coursetitle: "CHEM 448A Directed Studies in Chemistry - T1 DST CHEMISTRY",
        coursedept:	"CHEM",
        coursenumber: "448A",
        sectiontitle: "CHEM 448A 100",
        status: "Blocked",
        activity: "Directed Studies",
        prof: "",
        term: "1",
        day: "",
        starttime: "",
        endtime: ""
    }
];
